name: Website Deploy, Static CI

on:
  push:
    branches: [main]

env:
  PACKAGE_PATH: "build"
  NODE_VERSION: "12.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Auth to GH Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc

      - name: NPM Install and Build
        run: |
          npm install --ignore-scripts
          npm run build --if-present
        env:
          CI: false

      - name: Upload to Static Host Site
        run: |
          az storage blob upload-batch -d '$web' -s '${{ env.PACKAGE_PATH }}' --connection-string '${{ secrets.AZ_STORAGE_CONNSTRING }}'

    # - name: Purge CDN
    #   run: |
    #       curl -X POST "${{ secrets.PURGE_URL }}" -H "Content-Type: application/json" --data '{}'
